use proto_scan::read::IoRead;
use proto_scan::scan::field::Save;
use proto_scan::scan::{ScanMessage, ScannerBuilder};

mod proto {
    //! Protobuf code generated by [`prost`].
    //!
    //! with an additional [`proto_scan::ScanMessage`] derive attached.

    #[derive(::proto_scan::ScanMessage, Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Contact {
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(message, optional, tag = "2")]
        pub address: ::core::option::Option<Address>,
    }

    #[derive(::proto_scan::ScanMessage, Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Address {
        #[prost(string, tag = "1")]
        pub street: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub city: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub state: ::prost::alloc::string::String,
        #[prost(int32, tag = "4")]
        pub zip_code: i32,
    }
}

/// Reads a [proto::Contact] message from the file name argument, extracts
/// the zip code from the [`proto::Address`], and prints it to stdout.
fn main() {
    let scanner = proto::Contact::scanner().address(proto::Address::scanner().zip_code(Save));

    let filename = std::env::args()
        .skip(1)
        .next()
        .expect("no filename provided");

    let reader = IoRead::new_buffered(std::fs::File::open(filename).unwrap());
    let output = scanner.scan(reader).read_all().unwrap();
    let proto::ScanContactOutput {
        address: proto::ScanAddressOutput { zip_code, .. },
        ..
    } = output;

    println!("zip code: {zip_code}");
}
