//! Scanning protobuf message contents as event streams.
//!
//! This crate provides two methods of streaming access to the contents of a
//! protobuf message stream. The parse event stream API provides [low-level]
//! typed access to the protobuf wire format, while the [high-level] scan API
//! enables reading an event stream with conventional protobuf message
//! semantics.
//!
//! # Low-level: parse event stream
//!
//! The low-level event interface uses [`wire::ParseEventReader`] to read
//! protobuf wire format tags from a [`read::Read`] implementation:
//! ```
//! # use proto_scan::*;
//! use wire::ParseEventReader;
//! fn read_a<R: read::Read>(
//!     r: R,
//! ) -> Result<Option<i64>, DecodeError<<R::ReadTypes as read::ReadError>::Error>> {
//!     // From the protobuf documentation encoding guide.
//!     // message Test1 {
//!     //   int64 a = 1;
//!     // }
//!     let mut reader = wire::parse(r);
//!     let mut found_a = None;
//!     while let Some(event) = reader.next() {
//!         let (field_number, event) = event?;
//!         match event {
//!             wire::ParseEvent::Numeric(s) if field_number == 1 => match s {
//!                 wire::NumericField::Varint(v) => {
//!                     found_a = Some(
//!                         // cast bits according to protobuf encoding format
//!                         v as i64,
//!                     )
//!                 }
//!                 wire::NumericField::I64(_) | wire::NumericField::I32(_) => found_a = None,
//!             },
//!             wire::ParseEvent::Numeric(_)
//!             | wire::ParseEvent::Group(_)
//!             | wire::ParseEvent::LengthDelimited(_) => {}
//!         }
//!     }
//!     Ok(found_a)
//! }
//!
//! fn main() {
//!     // From the protobuf documentation encoding guide, this is a Test message
//!     // with a = 150.
//!     const INPUT: &[u8] = &[0x08, 0x96, 0x01];
//!
//!     assert_eq!(read_a(&mut &INPUT[..]), Ok(Some(150)))
//! }
//! ```
//!
//! In this example, the `read_a` method scans the provided input for a tag with
//! a varint wire type and field number 1. The last one found, if any, is
//! returned. Any other tag types or fields are ignored. The input is a `&mut &[u8]`
//! which has an implementation of [`Read`](read::Read).
//!
//! # High-level: generated scanner types
//!
//! The high-level API allows treating a parse event stream as the contents of a
//! single protobuf message with typed fields. While usable on their own, the
//! types and traits in this crate are intended to be used by generated code
//! to provide extraction of individual fields from a message.
//!
//! With the `derive` feature enabled, this crate exports a `#[derive]` macro
//! that generate these message field extractors. The macro works with message
//! types generated by [`prost`]. For use without `prost`, the
//! [`proto-scan-build`] crate can be used to generate similar code from
//! protobuf message descriptors.
//!
//! Usage of the high-level scanner API looks like this:
//! ```
//! # use proto_scan::*;
//! use scan::{ScanMessage, ScannerBuilder};
//! // From the protobuf documentation encoding guide.
//! // message Test1 {
//! //   int64 a = 1;
//! // }
//! #[derive(ScanMessage)] // attach our derive macro to...
//! // the type definition generated by `prost`:
//! #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
//! pub struct Test1 {
//!     #[prost(int64, tag = "1")]
//!     pub a: i64,
//! }
//!
//! fn read_a<R: read::Read>(r: R) -> Result<Option<i64>, scan::StopScan> {
//!     let scanner = Test1::scanner().save_a();
//!     let ScanTest1Output { a } = scanner.scan(r).read_all()?;
//!     Ok(a)
//! }
//!
//! fn main() {
//!     // From the protobuf documentation encoding guide, this is a Test1 message
//!     // with a = 150.
//!     const INPUT: &[u8] = &[0x08, 0x96, 0x01];
//!
//!     assert_eq!(read_a(&mut &INPUT[..]), Ok(Some(150)))
//! }
//! ```
//!
//! Calling the [`scan::ScanMessage::scanner`] method from the impl generated
//! for `Test1` returns an instance of a generated builder type `ScanTest1`.
//! `ScanTest1` has a builder method `save_a` that produces a new `ScanTest1`.
//! When the built scanner processes the input, it records the value of the last
//! `a` field found in the input. When `ScanTest1`'s
//! [`read_all()`](scan::Scan::read_all) method is called, it returns (on
//! success) a `ScanTest1Output`. That generated type has a single field `a`
//! that contains the decoded output. Any other tag types or fields are ignored.
//! The input to `read_a` is a `&mut &[u8]` which has an implementation of
//! [`Read`](read::Read).
//!
//! ## Embedded messages
//!
//! The contents of embedded messages can be accessed by setting a scanner for the
//! message field:
//! ```
//! # use proto_scan::*;
//! use scan::{ScanMessage, ScannerBuilder};
//! // From the protobuf documentation encoding guide.
//! // message Test3 {
//! //   Test1 c = 3;
//! // }
//! # #[derive(ScanMessage)]
//! # #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
//! # pub struct Test1 {
//! #     #[prost(int64, tag = "1")]
//! #     pub a: i64,
//! # }
//! #[derive(ScanMessage)] // attach our derive macro to...
//! // the type definition generated by `prost`:
//! #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
//! pub struct Test3 {
//!     #[prost(message, optional, tag = "3")]
//!     pub c: ::core::option::Option<Test1>,
//! }
//!
//! fn read_a_from_c<R: read::Read>(r: R) -> Result<Option<i64>, scan::StopScan> {
//!     let scanner = Test3::scanner().scan_c(Test1::scanner().save_a());
//!     let ScanTest3Output {
//!         c: ScanTest1Output { a },
//!     } = scanner.scan(r).read_all()?;
//!     Ok(a)
//! }
//!
//! fn main() {
//!     // From the protobuf documentation encoding guide, this is a Test3 message
//!     // with c's a set to 150.
//!     const INPUT: &[u8] = &[0x1a, 0x03, 0x08, 0x96, 0x01];
//!
//!     assert_eq!(read_a_from_c(&mut &INPUT[..]), Ok(Some(150)))
//! }
//! ```
//!
//! [low-level]: #low-level-parse-event-stream
//! [high-level]: #high-level-generated-scanner-types
//! [`prost`]: https://docs.rs/prost/latest/prost/
//! [`proto-scan-build`]: https://docs.rs/proto-scan-build/latest/proto_scan_build/

#![cfg_attr(not(feature = "std"), no_std)]

pub mod read;
pub mod scan;
pub mod wire;

mod decode_error;
pub use decode_error::DecodeError;

#[cfg(feature = "derive")]
pub use proto_scan_derive::ScanMessage;
