//! This crate provides allocation-free access to fields in a protobuf message.
//! It's most useful when only one or two values are needed from a larger
//! message and the performance cost of deserializing the other fields or
//! embedded messages is prohibitive.
//! 
//! There are two ways of getting streaming access to the contents of a protobuf
//! message stream. The [high-level] scan API uses generated code to enable
//! reading an event stream with conventional protobuf message semantics, while the
//! low-level parse event stream API provides typed access to the protobuf wire
//! format.
//!
//! # High-level: generated scanner types
//!
//! With the `derive` feature enabled, this crate exports a `#[derive]` macro
//! that generate these message field extractors. The macro works with message
//! types generated by [`prost`]. For use without `prost`, the
//! [`proto-scan-build`] crate can be used to generate similar code from
//! protobuf message descriptors.
//!
//! Usage of this API is easiest to see from an example. Consider the following
//! protobuf message definition:
//! ```proto
//! message Contact {
//!   string name = 1;
//!   Address address = 2;
//! }
//!
//! message Address {
//!   string street = 1;
//!   string city = 2;
//!   string state = 3;
//!   int zip_code = 4;
//! }
//! ```
//!
//! Suppose only the zip code from a `Contact` needs to be extracted. The scanner
//! API makes that easy:
//! ```
//! mod proto {
//!     //! generated code...
//! #   #[derive(::proto_scan::ScanMessage, Clone, PartialEq, Eq, Hash, ::prost::Message)]
//! #   pub struct Contact {
//! #       #[prost(string, tag = "1")]
//! #       pub name: ::prost::alloc::string::String,
//! #       #[prost(message, optional, tag = "2")]
//! #       pub address: ::core::option::Option<Address>,
//! #   }
//! #   #[derive(::proto_scan::ScanMessage, Clone, PartialEq, Eq, Hash, ::prost::Message)]
//! #   pub struct Address {
//! #       #[prost(string, tag = "1")]
//! #       pub street: ::prost::alloc::string::String,
//! #       #[prost(string, tag = "2")]
//! #       pub city: ::prost::alloc::string::String,
//! #       #[prost(string, tag = "3")]
//! #       pub state: ::prost::alloc::string::String,
//! #       #[prost(int32, tag = "4")]
//! #       pub zip_code: i32,
//! #   }
//! }
//!
//! # use proto_scan::*;
//! use scan::{ScanMessage, ScannerBuilder, field::Save};
//!
//! fn read_zip<R: read::Read>(
//!     reader: R,
//! ) -> Result<Option<i32>, scan::ScanError<<R::ReadTypes as read::ReadError>::Error>> {
//!    let scanner = proto::Contact::scanner().address(proto::Address::scanner().zip_code(Save));
//!    let proto::ScanContactOutput {
//!        address: proto::ScanAddressOutput { zip_code, .. },
//!        ..
//!    } = scanner.scan(reader).read_all()?;
//!
//!    Ok(zip_code)
//! }
//! ```
//!
//! For more on the high-level API, see the documentation for the [`scan`] module.
//!
//! # Low-level: parse event stream
//!
//! The low-level event interface uses [`wire::ParseEventReader`] to read
//! protobuf wire format tags from a [`read::Read`] implementation. For more,
//! including example usage, see the documentation for the [`wire`] module.
//!
//! [low-level]: #low-level-parse-event-stream
//! [high-level]: #high-level-generated-scanner-types
//! [`prost`]: https://docs.rs/prost/latest/prost/
//! [`proto-scan-build`]: https://docs.rs/proto-scan-build/latest/proto_scan_build/

#![cfg_attr(not(feature = "std"), no_std)]

pub mod read;
pub mod scan;
pub mod wire;

mod decode_error;
pub use decode_error::DecodeError;

#[cfg(feature = "derive")]
pub use proto_scan_derive::ScanMessage;
