//! The high-level message scanning API relies on generated code working in
//! conjuction with the types and traits in this module. It allows treating a
//! parse event stream as the contents of a single protobuf message with typed
//! fields.
//!
//! # Top-level message fields
//! Reading a field from a message looks like this:
//! ```
//! # use proto_scan::*;
//! use scan::{ScanMessage, ScannerBuilder};
//! // From the protobuf documentation encoding guide.
//! // message Test1 {
//! //   int64 a = 1;
//! // }
//! #[derive(ScanMessage)] // attach our derive macro to...
//! // the type definition generated by `prost`:
//! #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
//! pub struct Test1 {
//!     #[prost(int64, tag = "1")]
//!     pub a: i64,
//! }
//!
//! fn read_a<R: read::Read>(
//!     r: R,
//! ) -> Result<Option<i64>, scan::ScanError<<R::ReadTypes as read::ReadError>::Error>> {
//!     let scanner = Test1::scanner().a(scan::field::Save);
//!     let ScanTest1Output { a } = scanner.scan(r).read_all()?;
//!     Ok(a)
//! }
//!
//! fn main() {
//!     // From the protobuf documentation encoding guide, this is a Test1 message
//!     // with a = 150.
//!     const INPUT: &[u8] = &[0x08, 0x96, 0x01];
//!
//!     assert_eq!(read_a(&mut &INPUT[..]), Ok(Some(150)))
//! }
//! ```
//!
//! Calling the [`ScanMessage::scanner`] method from the impl generated for
//! `Test1` returns an instance of a generated builder type `ScanTest1`.
//! `ScanTest1` has a builder method `a` that takes a scanner (here
//! [`field::Save`]) and produces a new `ScanTest1`.  When the built scanner
//! processes the input, it records the value of the last `a` field found in the
//! input. When `ScanTest1`'s [`read_all()`](Scan::read_all) method is called,
//! it returns (on success) a `ScanTest1Output`. That generated type has a
//! single field `a` that contains the decoded output. Any other tag types or
//! fields are ignored.  The input to `read_a` is a `&mut &[u8]` which has an
//! implementation of [`Read`](crate::read::Read).
//!
//! # Embedded messages
//!
//! The contents of embedded messages can be accessed by setting a scanner for the
//! message field:
//! ```
//! # use proto_scan::*;
//! use scan::{ScanMessage, ScannerBuilder};
//! // From the protobuf documentation encoding guide.
//! // message Test3 {
//! //   Test1 c = 3;
//! // }
//! # #[derive(ScanMessage)]
//! # #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
//! # pub struct Test1 {
//! #     #[prost(int64, tag = "1")]
//! #     pub a: i64,
//! # }
//! #[derive(ScanMessage)] // attach our derive macro to...
//! // the type definition generated by `prost`:
//! #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
//! pub struct Test3 {
//!     #[prost(message, optional, tag = "3")]
//!     pub c: ::core::option::Option<Test1>,
//! }
//!
//! fn read_a_from_c<R: read::Read>(
//!     r: R,
//! ) -> Result<Option<i64>, scan::ScanError<<R::ReadTypes as read::ReadError>::Error>> {
//!     let scanner = Test3::scanner().c(Test1::scanner().a(scan::field::Save));
//!     let ScanTest3Output {
//!         c: ScanTest1Output { a },
//!     } = scanner.scan(r).read_all()?;
//!     Ok(a)
//! }
//!
//! # fn main() {
//! #     // From the protobuf documentation encoding guide, this is a Test3 message
//! #     // with c's a set to 150.
//! #     const INPUT: &[u8] = &[0x1a, 0x03, 0x08, 0x96, 0x01];
//! #     assert_eq!(read_a_from_c(&mut &INPUT[..]), Ok(Some(150)))
//! # }
//! ```
//!
//! The basic concept is the same, but instead of using the `Save` scanner for field `c`,
//! a scanner for the inner message type is provided instead. The output of that scanner
//! is provided as the output of `ScanTest3Output::c`.
//!
//! # Oneofs
//!
//! The contents of a oneof field group can be accessed by setting a scanner for
//! the group:
//! ```
//! # use proto_scan::*;
//! use scan::{ScanMessage, ScannerBuilder};
//! // From the protobuf documentation for oneofs.
//! // message SampleMessage {
//! //   oneof test_oneof {
//! //      string name = 4;
//! //      SubMessage sub_message = 9;
//! //   }
//! // }
//! //
//! // message SubMessage {}
//! // The type definitions generated by `prost`, with our derive macro attached:
//! #[derive(::proto_scan::ScanMessage, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
//! pub struct SubMessage {}
//! #[derive(::proto_scan::ScanMessage, Clone, PartialEq, Eq, Hash, ::prost::Message)]
//! pub struct SampleMessage {
//!     #[prost(oneof = "sample_message::TestOneof", tags = "4, 9")]
//!     pub test_oneof: ::core::option::Option<sample_message::TestOneof>,
//! }
//! /// Nested message and enum types in `SampleMessage`.
//! pub mod sample_message {
//!     #[derive(::proto_scan::ScanMessage, Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
//!     pub enum TestOneof {
//!         #[prost(string, tag = "4")]
//!         Name(::prost::alloc::string::String),
//!         #[prost(message, tag = "9")]
//!         SubMessage(super::SubMessage),
//!     }
//! }
//!
//! fn read_name<R: read::Read>(
//!     r: R,
//! ) -> Result<
//!     Option<<<R::ReadTypes as read::ReadTypes>::Buffer as read::ReadBuffer>::String>,
//!     scan::ScanError<<R::ReadTypes as read::ReadError>::Error>,
//! > {
//!     let scanner = SampleMessage::scanner()
//!         .test_oneof(sample_message::TestOneof::scanner().name(scan::field::Save));
//!     let ScanSampleMessageOutput { test_oneof } = scanner.scan(r).read_all()?;
//!
//!     Ok(match test_oneof {
//!         None => None,
//!         Some(sample_message::ScanTestOneofOutput::Name(name)) => name,
//!         Some(sample_message::ScanTestOneofOutput::SubMessage(())) => None,
//!     })
//! }
//!
//! # fn main() {
//! #     // Construct a sample input.
//! #     let input = {
//! #         let message = SampleMessage {
//! #             test_oneof: Some(sample_message::TestOneof::Name("Marco".to_owned())),
//! #         };
//! #         prost::Message::encode_to_vec(&message)
//! #     };
//! #     assert_eq!(read_name(&mut input.as_slice()), Ok(Some("Marco")))
//! # }
//! ```
//! 
//! # Maps
//! 
//! Like other field types, protobuf maps can be read by supplying a scanner for the field:
//! ```
//! // message WithMap {
//! //     map<i32, int32> i32_to_i32 = 1;
//! // }
//! # #[derive(Clone, PartialEq, ::prost::Message, ::proto_scan::ScanMessage)]
//! # pub struct WithMap {
//! #     #[prost(map = "int32, int32", tag = "1")]
//! #     pub i32_to_i32: ::std::collections::HashMap<i32, i32>,
//! # }
//! use std::collections::HashMap;
//! # use proto_scan::*;
//! use scan::{ScanMessage, ScannerBuilder};
//! 
//! fn read_map<R: read::Read>(r: R) -> Result<HashMap<i32, i32>, scan::ScanError<<R::ReadTypes as read::ReadError>::Error>> {
//!   let scanner = WithMap::scanner().i32_to_i32(scan::SaveMap::with_value(scan::field::Save));
//!   let ScanWithMapOutput { i32_to_i32 } = scanner.scan(r).read_all()?;
//!   Ok(i32_to_i32.into_iter().map(|(k, v)| (k, v.unwrap_or_default())).collect())
//! }
//! ``` 
//! 
//! Library support for scanners of maps is limited, but reading code can always
//! supply its own implementations of [`IntoScanner`] and
//! [`field::OnScanField`].
use crate::read::{ReadError, ReadTypes};
use crate::wire::{FieldNumber, GroupOp, I32, I64, NumericField, Varint};
use crate::wire::{LengthDelimited, ParseEvent, ParseEventReader};

mod builder;
pub use builder::ScannerBuilder;
pub mod encoding;
pub mod error;
pub use error::ScanError;
pub mod field;
mod map;
pub use map::{Map, SaveMap};
mod resettable;
pub use resettable::{IntoResettable, Resettable};
mod repeated;
pub use repeated::{
    Fold, RepeatStrategy, RepeatStrategyScanner, Repeated, SaveCloned, ScanRepeated, WriteCloned,
};
mod save_from;
pub use save_from::SaveFrom;

/// A message that can be scanned.
pub trait ScanMessage {
    /// The scanner for the message.
    type ScannerBuilder: ScannerBuilder<Self>;

    /// Creates a new scanner builder
    fn scanner() -> Self::ScannerBuilder;
}

/// A scanner for a protobuf message type.
///
/// This functions as a marker trait for scanner types that specifically scan
/// for messages (not fields or oneofs).
pub trait MessageScanner {
    /// The message type that this scanner can read.
    type Message: ScanMessage;
}

pub trait IntoScanner<T: ?Sized> {
    type Scanner<R: ReadTypes>: IntoScanOutput;
    fn into_scanner<R: ReadTypes>(self) -> Self::Scanner<R>;
}

pub trait IntoScanOutput {
    type ScanOutput;
    fn into_scan_output(self) -> Self::ScanOutput;
}

/// Callbacks for parse inputs encountered during a scan.
pub trait ScanCallbacks<R: ReadTypes, F = FieldNumber>: IntoScanOutput {
    type ScanEvent;

    /// Called when a numeric field is parsed.
    fn on_numeric(
        &mut self,
        field: F,
        value: NumericField,
    ) -> Result<Self::ScanEvent, ScanError<R::Error>>;

    /// Called when a SGROUP or EGROUP tag is read.
    fn on_group(&mut self, field: F, op: GroupOp) -> Result<Self::ScanEvent, ScanError<R::Error>>;

    /// Called when a length-delimited field tag is encountered.
    fn on_length_delimited(
        &mut self,
        field: F,
        delimited: impl LengthDelimited<ReadTypes = R>,
    ) -> Result<Self::ScanEvent, ScanError<R::Error>>;
}

/// A oneof grouping in a message that can be scanned for.
pub trait ScannableOneOf {
    /// A discriminant for the oneof variants.
    ///
    /// This should be an enum with one variant for each proto field in the oneof.
    type FieldNumber;
}

/// A scan in progress.
pub struct Scan<P, S>(P, S);

impl<P, S> Scan<P, S> {
    pub fn new(input: P, scanner: S) -> Self {
        Self(input, scanner)
    }
}

/// [`IntoIterator::IntoIter`] type for [`Scan`].
///
/// Implements [`Iterator`] by applying events from a [`ParseEventReader`] to a
/// [`ScanCallbacks`] and yielding the resulting [`ScanCallbacks::ScanEvent`] or
/// an error.
pub struct IntoIter<P, S>(P, S);

type ParseEventReaderScanError<P> =
    ScanError<<<P as ParseEventReader>::ReadTypes as ReadError>::Error>;

impl<P: ParseEventReader, S: ScanCallbacks<P::ReadTypes>> IntoIterator for Scan<P, S> {
    type Item = Result<S::ScanEvent, ParseEventReaderScanError<P>>;
    type IntoIter = IntoIter<P, S>;

    fn into_iter(self) -> Self::IntoIter {
        IntoIter(self.0, self.1)
    }
}

impl<P: ParseEventReader, S: ScanCallbacks<P::ReadTypes>> Iterator for IntoIter<P, S> {
    type Item = Result<S::ScanEvent, ParseEventReaderScanError<P>>;
    fn next(
        &mut self,
    ) -> Option<Result<S::ScanEvent, ScanError<<P::ReadTypes as ReadError>::Error>>> {
        next_event(&mut self.0, &mut self.1)
    }
}

pub(crate) fn next_event<P: ParseEventReader, S: ScanCallbacks<P::ReadTypes>>(
    parse: &mut P,
    fields: &mut S,
) -> Option<Result<S::ScanEvent, ParseEventReaderScanError<P>>> {
    let (field_number, event) = match parse.next() {
        Some(Err(e)) => return Some(Err(e.into())),
        None => return None,
        Some(Ok(event)) => event,
    };

    let output = match event {
        ParseEvent::Numeric(numeric_field) => fields.on_numeric(field_number, numeric_field),
        ParseEvent::Group(group_op) => fields.on_group(field_number, group_op),
        ParseEvent::LengthDelimited(l) => fields.on_length_delimited(field_number, l),
    };
    Some(output)
}

impl<P: ParseEventReader, S: ScanCallbacks<P::ReadTypes>> Scan<P, S> {
    pub fn read_all(self) -> Result<S::ScanOutput, ParseEventReaderScanError<P>> {
        let mut it = self.into_iter();
        for r in it.by_ref() {
            let _ = r?;
        }
        Ok(it.1.into_scan_output())
    }
}
